-- Job history for the studio.
--
-- What lives here is the RECORD of a render: what was asked for, what the
-- factory printed, whether it passed QC, and which artifacts existed when it
-- finished. What does NOT live here is the video. Rendered media is served
-- straight off the sandbox that produced it and downloaded as-is; nothing
-- copies those bytes into storage. That keeps this table small and permanent
-- while the multi-gigabyte sandbox snapshots stay disposable.
--
-- Consequence worth stating plainly: a job row outlives its downloads. Once the
-- sandbox snapshot is pruned (24h; see web/lib/sandbox.ts), the row is still
-- here and still shows the log, the QC report and the script — but the mp4 is
-- gone for good and has to be re-rendered from `video_json`.
--
-- Apply with:  supabase db push        (or paste into the SQL editor)

create table if not exists public.jobs (
  -- The sandbox name. Generated by newJobId(); doubles as the sandbox handle,
  -- which is why it is the primary key rather than a surrogate id.
  id            text primary key,
  slug          text        not null,
  title         text        not null,
  status        text        not null check (status in ('starting','running','done','failed')),
  created_at    timestamptz not null default now(),
  finished_at   timestamptz,
  exit_code     integer,

  -- Names only, e.g. ["final.mp4","captions.srt"] — never the bytes. Records
  -- what the render produced even after the sandbox is gone.
  artifacts     text[]      not null default '{}',

  -- Build output and QC report, mirrored out of the sandbox by the poller so
  -- they survive it.
  log           text        not null default '',
  qc            text,

  -- The inputs, so a job whose artifacts have expired can be re-rendered
  -- without retyping it. Null for bundled episodes, which are committed in the
  -- repo and need no copy here.
  video_json    jsonb,
  render_scenes text,
  source        jsonb
);

-- Note there is no `downloadable` column. Whether the artifacts can still be
-- fetched depends on the sandbox snapshot behind them, and a snapshot record
-- carries a session id rather than the sandbox name a job is keyed by — so
-- nothing could keep such a column honest. lib/db.ts derives it from created_at
-- against the same 24h TTL instead.

-- The list view is "newest first", and it is the only ordering the UI asks for.
create index if not exists jobs_created_at_idx on public.jobs (created_at desc);
create index if not exists jobs_slug_idx on public.jobs (slug);

alter table public.jobs enable row level security;

-- No policies are defined on purpose. With RLS on and no policy, the anon and
-- authenticated keys can read nothing, while the service role bypasses RLS
-- entirely. Only the Next.js server touches this table, and it holds the
-- service key — so the table is server-only until real user accounts exist, at
-- which point add an owner column and a policy rather than loosening this.
